package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resources",
    srcs = [
        "config/application.yaml",
        "data.sql",
        "log4j2.yaml",
        "schema.sql",
    ],
)
