DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    GIVEN_NAME VARCHAR(255) NOT NULL,
    SURNAME    VARCHAR(255) DEFAULT NULL
);

CREATE TABLE EMAIL_ADDRESS
(
    ADDRESS   VARCHAR(255) PRIMARY KEY,
    PERSON_ID BIGINT,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
);
