package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resources",
    srcs = [
        "config/application-test.yaml",
        "data-test.sql",
        "log4j2-test.yaml",
    ],
)
